### ISSUE TITLE
Obese male: Obj. file?

### ISSUE THREAD

**Issue by ASchwad** [eh3rrera/ARKitAnimation#3]
Thanks a lot for this repo!

Could you also add the raw obj file to the repo? I would like to add some other animations.

Not really an issue, but i dont know how else i could reach out to you...

Thanks in advance!

**Comment by eh3rrera** [comment]
Hi, I'm sorry, I can see the model is not available anymore. Since it was a copyright material, I didn't have the permission to distribute it in its raw format and I don't have the original file anymore.

Overall, I see that now it's harder to get quality free 3d models.

But you can also use one the models included in the [Mixamo library](https://www.mixamo.com/#/?page=1&type=Character). [This model](https://www.turbosquid.com/3d-models/obj-raymond-mustache/958777) I found searching for the other model looks good too.

**Comment by ASchwad** [comment]
Thanks for your answer @eh3rrera. 
The obese guy perfectly fits the needs of my university project (therefore non-commercial and never released app)

I managed to transform the .dae file with blender to an .obj and add some other animations in Mixamo. But you are right, since its not publicly available anymore, we should not merge the .obj file into this repo. Thanks again for your efforts!

**Comment by eh3rrera** [comment]
Great 👍
